CREATE DATABASE yeticave
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;

USE yeticave;

CREATE TABLE category (
id INT AUTO_INCREMENT PRIMARY KEY,
category_name VARCHAR(128) NOT NULL UNIQUE,
code VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE lot (
id INT AUTO_INCREMENT PRIMARY KEY,
create_data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
lot_name TEXT NOT NULL,
lot_description TEXT NOT NULL,
photo TEXT,
start_price INT NOT NULL,
date_expiration TIMESTAMP,
lot_step INT NOT NULL
);

CREATE TABLE bet (
id INT AUTO_INCREMENT PRIMARY KEY,
date_bet TIMESTAMP,
sum_bet INT NOT NULL
);

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
user_born TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
email VARCHAR(128) NOT NULL UNIQUE,
user_name VARCHAR(128) NOT NULL UNIQUE,
user_password VARCHAR(128) NOT NULL UNIQUE,
contacts VARCHAR(128)
);
